openapi: 3.0.0
info:
  title: example
  version: '1.0'
  description: Soem API
servers:
  - url: 'http://localhost:3000'
paths:
  /example/hello:
    get:
      summary: get hello
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'http://localhost:8080/api/nodes.raw?srn=gh/s-bhupathiraju/sample-repo/models/example.yaml&mid=4'
              examples:
                example-1: {}
components:
  schemas: {}
