openapi: 3.0.0
info:
  title: example
  version: '1.0'
  description: Soem API
servers:
  - url: 'http://localhost:3000'
paths:
  /example/hello:
    get:
      summary: get hello
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
              examples:
                example-1: {}
components:
  schemas: {}
